### ISSUE TITLE
关于sql文件创建数据异常

### ISSUE THREAD

**Issue by pangPython** [cnsecer/ThinkAdmin#2]
直接使用项目中的sql文件运行phpMyAdmin--SQL会报错
删除sql文件中类似“LOCK TABLES `category` WRITE;”/“UNLOCK TABLES;”的行，然后去运行就没有错误了

后台很简洁,很棒！加油！

**Comment by rootphantomer** [comment]
@pangPython 我直接用navicat导入没啥问题

**Comment by pangPython** [comment]
嗯，我用的是phpMyAdmin，不知道咋回事
